[package]
name = "seonbi"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["freeze-dict"]
freeze-dict = []

[dependencies]
nom.workspace = true
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
pulldown-cmark.workspace = true
pulldown-cmark-to-cmark.workspace = true
csv.workspace = true
thiserror.workspace = true
html-escape.workspace = true
htmlentity.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
