[package]
name = "wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository = "https://github.com/moreal/seonbi-rs"
homepage = "https://github.com/moreal/seonbi-rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
seonbi = { path = "../seonbi" }
serde.workspace = true
wasm-bindgen.workspace = true
serde-wasm-bindgen.workspace = true
tsify.workspace = true
js-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
